---
apiVersion: v1
kind: Service
metadata:
  name: invoice-app
  labels:
        app: invoice-app
        tier: frontend
spec:
  type: NodePort
  selector:
    app: invoice-app
  externalTrafficPolicy: Local
  sessionAffinity: "ClientIP"
  sessionAffinityConfig:
    clientIP: 
      timeoutSeconds: 10
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
---
apiVersion: v1 
kind: ConfigMap 
metadata:
  name: invoice-app
data:
  payment-provider-url: http://payment-provider:8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invoice-app
  template:
    metadata:
      labels:
        app: invoice-app
        tier: frontend
    spec:
      containers:
      - name: main
        image: invoice-app:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081
        envFrom:
          - configMapRef:
              name: invoice-app
